apply plugin: 'com.android.application'

android {
    namespace 'com.ssps6210.familydiner'
    compileSdk 34
    defaultConfig {
        applicationId 'com.ssps6210.familydiner'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        debug  { debuggable true }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
